export interface OfflineWord {
  id: string;
  text: string;
  normalizedText: string;
  length: number;
  category: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
}

export interface OfflineChapter {
  id: string;
  chapterNumber: number;
  title: string;
  narrative: string; // Long, engaging story narrative
  category: string;
  unlockComicImageUrl: string;
  words: OfflineWord[];
}

export const INITIAL_OFFLINE_CHAPTERS: OfflineChapter[] = [
  {
    id: "off_ch_1",
    chapterNumber: 1,
    title: "Chapter 1: Jejak Sejarah di Jantung Kota Jakarta",
    category: "Sejarah & Nasional",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&auto=format&fit=crop&q=80",
    narrative: "Di tengah hiruk-pikuk kota metropolitan Jakarta yang tak pernah tidur, Kapten Klu berdiri di puncak Lapangan Medan Merdeka. Angin malam berhembus membawa kehangatan kota. Di hadapannya menjulang tugu kebanggaan bangsa yang mahkotanya dilapisi emas murni. Namun malam ini, cakar misterius Bayangan meninggalkan teka-teki kuno di sekitar kawasan bersejarah. Untuk mengungkap rahasianya, Kapten Klu harus memecahkan 5 simbol kata tentang kebanggaan Nusantara!",
    words: [
      { id: "off_w1_1", text: "KOMIK", normalizedText: "KOMIK", length: 5, category: "Literasi", difficulty: "EASY" },
      { id: "off_w1_2", text: "MONAS", normalizedText: "MONAS", length: 5, category: "Sejarah", difficulty: "EASY" },
      { id: "off_w1_3", text: "TINTA", normalizedText: "TINTA", length: 5, category: "Peralatan", difficulty: "EASY" },
      { id: "off_w1_4", text: "DINDING", normalizedText: "DINDING", length: 7, category: "Arsitektur", difficulty: "MEDIUM" },
      { id: "off_w1_5", text: "GARUDA", normalizedText: "GARUDA", length: 6, category: "Nasional", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_2",
    chapterNumber: 2,
    title: "Chapter 2: Keajaiban Mahakarya Candi Borobudur",
    category: "Arsitektur & Budaya",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&auto=format&fit=crop&q=80",
    narrative: "Perjalanan berlanjut menuju lembah Magelang yang diselimuti kabut pagi nan damai. Di antara pepohonan hijau rindang, berdirilah candi Buddha terbesar di dunia peninggalan Dinasti Syailendra abad ke-8. Ribuan panel relief terukir indah pada dinding-dinding batu vulkanik, menceritakan falsafah kehidupan manusia. Bayangan sengaja menyembunyikan kunci komik di antara stupa-stupa batu berongga. Kapten Klu harus menganalisis setiap detail arsitektur purba ini!",
    words: [
      { id: "off_w2_1", text: "BOROBUDUR", normalizedText: "BOROBUDUR", length: 9, category: "Sejarah", difficulty: "MEDIUM" },
      { id: "off_w2_2", text: "CANDI", normalizedText: "CANDI", length: 5, category: "Arsitektur", difficulty: "EASY" },
      { id: "off_w2_3", text: "STUPA", normalizedText: "STUPA", length: 5, category: "Arsitektur", difficulty: "MEDIUM" },
      { id: "off_w2_4", text: "RELIEF", normalizedText: "RELIEF", length: 6, category: "Kesenian", difficulty: "HARD" },
      { id: "off_w2_5", text: "PATUNG", normalizedText: "PATUNG", length: 6, category: "Kesenian", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_3",
    chapterNumber: 3,
    title: "Chapter 3: Pesona Vulkanik Danau Toba",
    category: "Geografi & Alam",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&auto=format&fit=crop&q=80",
    narrative: "Menyeberang ke Pulau Sumatra, udara dingin danau vulkanik raksasa menyapa Kapten Klu. Terbentuk dari letusan dahsyat gunung super purba ratusan ribu tahun lalu, Danau Toba membentang luas dengan Pulau Samosir yang anggun di tengahnya. Di sini, kekayaan kebudayaan Batak dan keajaiban alam menyatu. Bayangan menantang kecerdasan detektif dengan teka-teki seputar pembentukan danau vulkanik dan keindahan alam Sumatra!",
    words: [
      { id: "off_w3_1", text: "TOBA", normalizedText: "TOBA", length: 4, category: "Geografi", difficulty: "EASY" },
      { id: "off_w3_2", text: "DANAU", normalizedText: "DANAU", length: 5, category: "Geografi", difficulty: "EASY" },
      { id: "off_w3_3", text: "VULKANIK", normalizedText: "VULKANIK", length: 8, category: "Sains", difficulty: "HARD" },
      { id: "off_w3_4", text: "PULAU", normalizedText: "PULAU", length: 5, category: "Geografi", difficulty: "EASY" },
      { id: "off_w3_5", text: "SAMOSIR", normalizedText: "SAMOSIR", length: 7, category: "Geografi", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_4",
    chapterNumber: 4,
    title: "Chapter 4: Surga Bahari Raja Ampat",
    category: "Kelautan & Ekosistem",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800&auto=format&fit=crop&q=80",
    narrative: "Kapten Klu terbang ke ujung timur Nusantara, menatap gugusan pulau karang zamrud di atas lautan biru jernih Raja Ampat, Papua. Lautan ini adalah rumah bagi 75% spesies koral dunia dan ribuan jenis ikan tropis yang berwarna-warni. Di balik labirin gugusan pulau karst nan memukau ini, Bayangan menyembunyikan rahasia samudra yang hanya bisa dipecahkan oleh penjelajah berwawasan luas!",
    words: [
      { id: "off_w4_1", text: "AMPAT", normalizedText: "AMPAT", length: 5, category: "Geografi", difficulty: "EASY" },
      { id: "off_w4_2", text: "TERUMBU", normalizedText: "TERUMBU", length: 7, category: "Kelautan", difficulty: "MEDIUM" },
      { id: "off_w4_3", text: "KARANG", normalizedText: "KARANG", length: 6, category: "Kelautan", difficulty: "EASY" },
      { id: "off_w4_4", text: "LAUT", normalizedText: "LAUT", length: 4, category: "Geografi", difficulty: "EASY" },
      { id: "off_w4_5", text: "SELAM", normalizedText: "SELAM", length: 5, category: "Olahraga", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_5",
    chapterNumber: 5,
    title: "Chapter 5: Warisan Budaya Lukis Batik",
    category: "Budaya & Kesenian",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80",
    narrative: "Masuk ke sebuah sanggar seni tradisional di Solo dan Yogyakarta, bau khas lilin malam panas menyeruak di udara. Para pengrajin dengan teliti menorehkan cairan malam menggunakan alat canting kuno di atas kain putih halus. Setiap motif batik memuat filosofi mendalam, mulai dari Parang hingga Kawung. Kapten Klu mengamati bahwa pesan rahasia Bayangan tersembunyi di balik simetrisnya corak seni lukis kain warisan dunia ini!",
    words: [
      { id: "off_w5_1", text: "BATIK", normalizedText: "BATIK", length: 5, category: "Budaya", difficulty: "EASY" },
      { id: "off_w5_2", text: "CANTING", normalizedText: "CANTING", length: 7, category: "Peralatan", difficulty: "MEDIUM" },
      { id: "off_w5_3", text: "KAIN", normalizedText: "KAIN", length: 4, category: "Material", difficulty: "EASY" },
      { id: "off_w5_4", text: "MOTIF", normalizedText: "MOTIF", length: 5, category: "Kesenian", difficulty: "EASY" },
      { id: "off_w5_5", text: "NATIVE", normalizedText: "NATIVE", length: 6, category: "Istilah", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_6",
    chapterNumber: 6,
    title: "Chapter 6: Seni Pertunjukan Wayang Kulit",
    category: "Budaya & Teater",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80",
    narrative: "Layar kelir terbentang putih diiringi alunan lembut musik gamelan Jawa. Di balik layar, sang Dalang menggerakkan pahatan tokoh wayang kulit dengan cekatan. Bayangan hitam yang terpantul dari lampu blencong menceritakan wiracarita kepahlawanan kuno Ramayana dan Mahabharata. Kapten Klu duduk di barisan depan untuk membaca makna tersirat di balik kisah kepemimpinan dan kebijaksanaan ini!",
    words: [
      { id: "off_w6_1", text: "WAYANG", normalizedText: "WAYANG", length: 6, category: "Budaya", difficulty: "EASY" },
      { id: "off_w6_2", text: "DALANG", normalizedText: "DALANG", length: 6, category: "Profesi", difficulty: "MEDIUM" },
      { id: "off_w6_3", text: "KELIR", normalizedText: "KELIR", length: 5, category: "Peralatan", difficulty: "HARD" },
      { id: "off_w6_4", text: "GAMELAN", normalizedText: "GAMELAN", length: 7, category: "Musik", difficulty: "MEDIUM" },
      { id: "off_w6_5", text: "LAKON", normalizedText: "LAKON", length: 5, category: "Kesenian", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_7",
    chapterNumber: 7,
    title: "Chapter 7: Harmoni Musik Pipa Bambu Angklung",
    category: "Musik & Alat Tradisional",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80",
    narrative: "Di Saung Udjo Jawa Barat, riuh suaran getaran bambu saling bersahutan membentuk harmoni musik melodi yang indah. Angklung, alat musik dari susunan pipa bambu berongga, menghasilkan nada khas saat digoyangkan. Diakui oleh UNESCO sebagai Warisan Budaya Takbenda, musik angklung mengajarkan bahwa keindahan sejati tercipta dari kerja sama dan kekompakan tim, sama seperti misi Kapten Klu memecahkan teka-teki!",
    words: [
      { id: "off_w7_1", text: "ANGKLUNG", normalizedText: "ANGKLUNG", length: 8, category: "Musik", difficulty: "MEDIUM" },
      { id: "off_w7_2", text: "BAMBU", normalizedText: "BAMBU", length: 5, category: "Tanaman", difficulty: "EASY" },
      { id: "off_w7_3", text: "NADA", normalizedText: "NADA", length: 4, category: "Musik", difficulty: "EASY" },
      { id: "off_w7_4", text: "MELODI", normalizedText: "MELODI", length: 6, category: "Musik", difficulty: "EASY" },
      { id: "off_w7_5", text: "MUSIK", normalizedText: "MUSIK", length: 5, category: "Kesenian", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_8",
    chapterNumber: 8,
    title: "Chapter 8: Cita Rasa Kuliner Gado-Gado",
    category: "Kuliner & Rempah",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80",
    narrative: "Aroma gurih saus kacang tumbuk dan minyak wijen memenuhi pasar tradisional khas Betawi. Di atas cobek batu besar, sayuran segar seperti bayam, kangkung, tauge, lontong, dan tahu diulek bersama saus kacang kaya rempah. Gado-gado sering dijuluki 'Salad khas Indonesia' yang menyehatkan dan lezat. Kapten Klu mencicipi sajian kuliner ini sambil mengurai petunjuk bahan dapur yang ditinggalkan Bayangan!",
    words: [
      { id: "off_w8_1", text: "GADO", normalizedText: "GADO", length: 4, category: "Kuliner", difficulty: "EASY" },
      { id: "off_w8_2", text: "KACANG", normalizedText: "KACANG", length: 6, category: "Bahan", difficulty: "EASY" },
      { id: "off_w8_3", text: "BUMBU", normalizedText: "BUMBU", length: 5, category: "Kuliner", difficulty: "EASY" },
      { id: "off_w8_4", text: "SAYUR", normalizedText: "SAYUR", length: 5, category: "Bahan", difficulty: "EASY" },
      { id: "off_w8_5", text: "KULINER", normalizedText: "KULINER", length: 7, category: "Gaya Hidup", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_9",
    chapterNumber: 9,
    title: "Chapter 9: Kelezatan Terenak Dunia Rendang",
    category: "Kuliner & Tradisi",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
    narrative: "Dari dapur Minangkabau di Sumatra Barat, harum aroma santan manis dan rempah-rempah olahan yang dimasak berjam-jam menyeruak ke sekeliling kota. Rendang daging telah dinobatkan sebagai salah satu hidangan terlezat di dunia oleh berbagai lembaga internasional. Proses memasaknya yang membutuhkan kesabaran tinggi mencerminkan ketekunan Kapten Klu dalam memecahkan teka-teki kata tersulit!",
    words: [
      { id: "off_w9_1", text: "RENDANG", normalizedText: "RENDANG", length: 7, category: "Kuliner", difficulty: "EASY" },
      { id: "off_w9_2", text: "DAGING", normalizedText: "DAGING", length: 6, category: "Bahan", difficulty: "EASY" },
      { id: "off_w9_3", text: "SANTAN", normalizedText: "SANTAN", length: 6, category: "Bahan", difficulty: "EASY" },
      { id: "off_w9_4", text: "REMPAH", normalizedText: "REMPAH", length: 6, category: "Bahan", difficulty: "MEDIUM" },
      { id: "off_w9_5", text: "PADANG", normalizedText: "PADANG", length: 6, category: "Geografi", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_10",
    chapterNumber: 10,
    title: "Chapter 10: Kadal Purba Raksasa Komodo",
    category: "Fauna & Konservasi",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&auto=format&fit=crop&q=80",
    narrative: "Langkah Kapten Klu menapak di pulau savana terjal Taman Nasional Komodo, Nusa Tenggara Timur. Di sini hidup kadal purba terbesar yang tersisa di muka bumi: Varanus komodoensis. Spesies endemik terlindungi ini dapat tumbuh hingga panjang 3 meter. Di antara hamparan rerumputan kering dan bukit-bukit eksotis, detektif mempelajari perilaku hewan purba ini untuk menemukan simbol rahasia!",
    words: [
      { id: "off_w10_1", text: "KOMODO", normalizedText: "KOMODO", length: 6, category: "Fauna", difficulty: "EASY" },
      { id: "off_w10_2", text: "NUSA", normalizedText: "NUSA", length: 4, category: "Istilah", difficulty: "EASY" },
      { id: "off_w10_3", text: "KADAL", normalizedText: "KADAL", length: 5, category: "Fauna", difficulty: "EASY" },
      { id: "off_w10_4", text: "KANIBAL", normalizedText: "KANIBAL", length: 7, category: "Biologi", difficulty: "HARD" },
      { id: "off_w10_5", text: "TAMAN", normalizedText: "TAMAN", length: 5, category: "Lokasi", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_11",
    chapterNumber: 11,
    title: "Chapter 11: Kerbau Kerdil Endemik Anoa",
    category: "Fauna & Hutan Tropis",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800&auto=format&fit=crop&q=80",
    narrative: "Menjelajahi kelebatan hutan hujan pegunungan Sulawesi, Kapten Klu mendeteksi keberadaan mamalia langka yang dilindungi. Anoa, kerbau kerdil dengan bentuk tubuh unik berukuran kecil dan tanduk runcing, hidup terisolasi di dalam rimba pedalaman. Kelangkaan satwa unik Nusantara ini memberikan inspirasi bagi sang detektif bahwa sesuatu yang kecil bisa menyimpan keunikan yang sangat besar!",
    words: [
      { id: "off_w11_1", text: "ANOA", normalizedText: "ANOA", length: 4, category: "Fauna", difficulty: "MEDIUM" },
      { id: "off_w11_2", text: "SULAWESI", normalizedText: "SULAWESI", length: 8, category: "Geografi", difficulty: "EASY" },
      { id: "off_w11_3", text: "MAMALIA", normalizedText: "MAMALIA", length: 7, category: "Biologi", difficulty: "MEDIUM" },
      { id: "off_w11_4", text: "TANDUK", normalizedText: "TANDUK", length: 6, category: "Biologi", difficulty: "EASY" },
      { id: "off_w11_5", text: "HUTAN", normalizedText: "HUTAN", length: 5, category: "Lingkungan", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_12",
    chapterNumber: 12,
    title: "Chapter 12: Pemangsa Loreng Harimau Sumatra",
    category: "Fauna & Suaka Margasatwa",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800&auto=format&fit=crop&q=80",
    narrative: "Jejak cakar tajam di batang pohon besar menandai wilayah kekuasaan Harimau Sumatra di dalam Taman Nasional Gunung Leuser. Pemangsa berbulu loreng oranye-hitam yang sangat agung ini merupakan subspesies harimau terakhir di Indonesia setelah punahnya harimau Jawa dan Bali. Kapten Klu bergerak hati-hati sambil menganalisis ekosistem hutan rimba pelestarian ini!",
    words: [
      { id: "off_w12_1", text: "HARIMAU", normalizedText: "HARIMAU", length: 7, category: "Fauna", difficulty: "EASY" },
      { id: "off_w12_2", text: "SUMATRA", normalizedText: "SUMATRA", length: 7, category: "Geografi", difficulty: "EASY" },
      { id: "off_w12_3", text: "LORENG", normalizedText: "LORENG", length: 6, category: "Pola", difficulty: "EASY" },
      { id: "off_w12_4", text: "RAKSASA", normalizedText: "RAKSASA", length: 7, category: "Ukuran", difficulty: "EASY" },
      { id: "off_w12_5", text: "RIMBA", normalizedText: "RIMBA", length: 5, category: "Lingkungan", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_13",
    chapterNumber: 13,
    title: "Chapter 13: Bunga Parasit Raksasa Rafflesia",
    category: "Botani & Keajaiban Alam",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=800&auto=format&fit=crop&q=80",
    narrative: "Di tengah kelembaban belantara Bengkulu, Kapten Klu menyaksikan fenomena botani langka. Bunga Rafflesia arnoldii mekar sempurna dengan diameter mahkota mencapai lebih dari 1 meter. Bunga parasit tanpa daun dan batang asli ini mengeluarkan aroma khas menyengat untuk menarik serangga penyerbuk. Keajaiban flora unik ini menjadi bukti betapa kaya dan ajaibnya alam Indonesia!",
    words: [
      { id: "off_w13_1", text: "RAFFLESIA", normalizedText: "RAFFLESIA", length: 9, category: "Botani", difficulty: "HARD" },
      { id: "off_w13_2", text: "RAWA", normalizedText: "RAWA", length: 4, category: "Lingkungan", difficulty: "EASY" },
      { id: "off_w13_3", text: "MEKAR", normalizedText: "MEKAR", length: 5, category: "Botani", difficulty: "EASY" },
      { id: "off_w13_4", text: "AROMA", normalizedText: "AROMA", length: 5, category: "Sensori", difficulty: "EASY" },
      { id: "off_w13_5", text: "BOTANI", normalizedText: "BOTANI", length: 6, category: "Sains", difficulty: "HARD" },
    ],
  },
  {
    id: "off_ch_14",
    chapterNumber: 14,
    title: "Chapter 14: Lautan Pasir & Kawah Gunung Bromo",
    category: "Geografi & Gunung Berapi",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&auto=format&fit=crop&q=80",
    narrative: "Menjelang fajar menyingsing, Kapten Klu menapakkan kaki di hamparan lautan pasir berbisik Gunung Bromo, Jawa Timur. Saat matahari terbit (sunrise) menyinari kawah vulkanik aktif yang mengeluarkan hembusan asap putih nipis, pemandangan dramatis seperti di planet lain tercipta. Bayangan sengaja meninggalkan teka-teki sains geografi di sekitar kawah suci masyarakat suku Tengger!",
    words: [
      { id: "off_w14_1", text: "BROMO", normalizedText: "BROMO", length: 5, category: "Geografi", difficulty: "EASY" },
      { id: "off_w14_2", text: "KAWAH", normalizedText: "KAWAH", length: 5, category: "Geografi", difficulty: "MEDIUM" },
      { id: "off_w14_3", text: "ERUPSI", normalizedText: "ERUPSI", length: 6, category: "Sains", difficulty: "HARD" },
      { id: "off_w14_4", text: "PASIR", normalizedText: "PASIR", length: 5, category: "Material", difficulty: "EASY" },
      { id: "off_w14_5", text: "SUNRISE", normalizedText: "SUNRISE", length: 7, category: "Fenomena", difficulty: "MEDIUM" },
    ],
  },
  {
    id: "off_ch_15",
    chapterNumber: 15,
    title: "Chapter 15: Sumpah Palapa Kejayaan Majapahit",
    category: "Sejarah & Kerajaan",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80",
    narrative: "Kapten Klu mempelajari sisa-sisa kemegahan situs Trowulan di Trowulan, Jawa Timur, ibu kota Kerajaan Majapahit abad ke-14. Di tempat inilah Mahapatih Gajah Mada mengumandangkan Sumpah Palapa yang legendaris di hadapan Raja Hayam Wuruk untuk menyatukan seluruh kepulauan Nusantara di bawah panji kejayaan bangsa. Nilai sejarah dan semangat persatuan ini menjadi inspirasi utama penyelidikan detektif!",
    words: [
      { id: "off_w15_1", text: "MAJAPAHIT", normalizedText: "MAJAPAHIT", length: 9, category: "Sejarah", difficulty: "HARD" },
      { id: "off_w15_2", text: "SUMPAH", normalizedText: "SUMPAH", length: 6, category: "Sejarah", difficulty: "MEDIUM" },
      { id: "off_w15_3", text: "PALAPA", normalizedText: "PALAPA", length: 6, category: "Sejarah", difficulty: "MEDIUM" },
      { id: "off_w15_4", text: "HAYAM", normalizedText: "HAYAM", length: 5, category: "Sejarah", difficulty: "MEDIUM" },
      { id: "off_w15_5", text: "GAJAH", normalizedText: "GAJAH", length: 5, category: "Sejarah", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_16",
    chapterNumber: 16,
    title: "Chapter 16: Pembangunan Ibu Kota Nusantara (IKN)",
    category: "Modern & Infrastruktur",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
    narrative: "Melihat ke masa depan, Kapten Klu meninjau lanskap pembangunan Ibu Kota Nusantara (IKN) di Penajam Paser Utara, Kalimantan Timur. Dirancang sebagai kota hutan yang hijau, cerdas (Smart City), dan berkelanjutan, IKN menjadi simbol lompatan peradaban Indonesia modern menuju Indonesia Emas 2045. Di lokasi pembangunan futuristik ini, teka-teki sains dan teknologi terkini menunggu untuk dipecahkan!",
    words: [
      { id: "off_w16_1", text: "IKN", normalizedText: "IKN", length: 3, category: "Modern", difficulty: "EASY" },
      { id: "off_w16_2", text: "PENAJAM", normalizedText: "PENAJAM", length: 7, category: "Geografi", difficulty: "HARD" },
      { id: "off_w16_3", text: "BORNEO", normalizedText: "BORNEO", length: 6, category: "Geografi", difficulty: "MEDIUM" },
      { id: "off_w16_4", text: "MODERN", normalizedText: "MODERN", length: 6, category: "Konsep", difficulty: "EASY" },
      { id: "off_w16_5", text: "SMARTHUB", normalizedText: "SMARTHUB", length: 8, category: "Teknologi", difficulty: "HARD" },
    ],
  },
  {
    id: "off_ch_17",
    chapterNumber: 17,
    title: "Chapter 17: Penjelajahan Luar Angkasa & Astronomi",
    category: "Sains & Antariksa",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    narrative: "Mengarahkan teropong bintang ke langit malam yang bertabur miliaran galaksi, Kapten Klu meneliti misteri tata surya dan jagat raya. Mulai dari planet terdekat seperti Mars dan Jupiter, bintang raksasa, hingga hukum gravitasi universal yang dirumuskan oleh para ilmuwan dunia. Pemahaman tentang ilmu astronomi antariksa membantu detektif mengerti posisi Bumi di tengah alam semesta yang luas tak bertepi!",
    words: [
      { id: "off_w17_1", text: "PLANET", normalizedText: "PLANET", length: 6, category: "Astronomi", difficulty: "EASY" },
      { id: "off_w17_2", text: "GRAVITASI", normalizedText: "GRAVITASI", length: 9, category: "Fisika", difficulty: "HARD" },
      { id: "off_w17_3", text: "GALAKSI", normalizedText: "GALAKSI", length: 7, category: "Antariksa", difficulty: "MEDIUM" },
      { id: "off_w17_4", text: "BINTANG", normalizedText: "BINTANG", length: 7, category: "Astronomi", difficulty: "EASY" },
      { id: "off_w17_5", text: "ORBIT", normalizedText: "ORBIT", length: 5, category: "Sains", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_18",
    chapterNumber: 18,
    title: "Chapter 18: Keanekaragaman Energi Terbarukan",
    category: "Sains & Teknologi",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&auto=format&fit=crop&q=80",
    narrative: "Kapten Klu berkunjung ke ladang turbin angin dan panel surya raksasa yang memanfaatkan kekuatan alam untuk menghasilkan energi bersih ramah lingkungan. Transisi dari bahan bakar fosil menuju energi terbarukan seperti angin, matahari, dan panas bumi (geotermal) merupakan langkah penting menyelamatkan planet Bumi dari pemanasan global. Pengetahuan teknologi hijau ini menjadi petunjuk berharga bagi detektif!",
    words: [
      { id: "off_w18_1", text: "ENERGY", normalizedText: "ENERGY", length: 6, category: "Sains", difficulty: "EASY" },
      { id: "off_w18_2", text: "TURBIN", normalizedText: "TURBIN", length: 6, category: "Teknologi", difficulty: "MEDIUM" },
      { id: "off_w18_3", text: "SURYA", normalizedText: "SURYA", length: 5, category: "Sains", difficulty: "EASY" },
      { id: "off_w18_4", text: "BIOMASSA", normalizedText: "BIOMASSA", length: 8, category: "Lingkungan", difficulty: "HARD" },
      { id: "off_w18_5", text: "PANAS", normalizedText: "PANAS", length: 5, category: "Fisika", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_19",
    chapterNumber: 19,
    title: "Chapter 19: Penemuan Komputer & Dunia Digital",
    category: "Teknologi & Informatika",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
    narrative: "Di dalam ruang laboratorium komputasi modern, Kapten Klu meneliti evolusi mesin penemu komputer dari mikroprosesor pertama hingga era kecerdasan buatan (Artificial Intelligence) dan algoritma jaringan global. Dunia digital saat ini memungkinkan jutaan manusia terhubung dalam hitungan milidetik. Pemahaman tentang jaringan internet dan sistem biner membantu detektif membongkar enkripsi teka-teki paling rumit!",
    words: [
      { id: "off_w19_1", text: "CODING", normalizedText: "CODING", length: 6, category: "Teknologi", difficulty: "EASY" },
      { id: "off_w19_2", text: "SERVER", normalizedText: "SERVER", length: 6, category: "Informatika", difficulty: "MEDIUM" },
      { id: "off_w19_3", text: "DIGITAL", normalizedText: "DIGITAL", length: 7, category: "Teknologi", difficulty: "EASY" },
      { id: "off_w19_4", text: "MEMORY", normalizedText: "MEMORY", length: 6, category: "Informatika", difficulty: "MEDIUM" },
      { id: "off_w19_5", text: "ROBOT", normalizedText: "ROBOT", length: 5, category: "Teknologi", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_20",
    chapterNumber: 20,
    title: "Chapter 20: Sastra & Karya Pujangga Nusantara",
    category: "Literasi & Kebudayaan",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80",
    narrative: "Membuka lembaran perpustakaan tua, Kapten Klu membaca bait-bait puisi dan novel karya pujangga ternama Nusantara seperti Chairil Anwar dan Pramoedya Ananta Toer. Karya literasi dan bahasa tidak hanya menghibur, tetapi juga memicu kesadaran bangsa dan memperkaya kosa kata. Memahami indahnya gaya bahasa majas dan gurindam menjadi kunci detektif menemukan kebenaran di balik permainan kata!",
    words: [
      { id: "off_w20_1", text: "PUISI", normalizedText: "PUISI", length: 5, category: "Literasi", difficulty: "EASY" },
      { id: "off_w20_2", text: "SASTRA", normalizedText: "SASTRA", length: 6, category: "Budaya", difficulty: "MEDIUM" },
      { id: "off_w20_3", text: "MAJAS", normalizedText: "MAJAS", length: 5, category: "Literasi", difficulty: "HARD" },
      { id: "off_w20_4", text: "NOVEL", normalizedText: "NOVEL", length: 5, category: "Literasi", difficulty: "EASY" },
      { id: "off_w20_5", text: "PENULIS", normalizedText: "PENULIS", length: 7, category: "Profesi", difficulty: "EASY" },
    ],
  },
  {
    id: "off_ch_21",
    chapterNumber: 21,
    title: "Chapter 21: Puncak Kebenaran & Pahlawan Kebaikan",
    category: "Pengetahuan Umum & Pahlawan",
    unlockComicImageUrl: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&auto=format&fit=crop&q=80",
    narrative: "Setelah melalui perjalanan panjang mengelilingi Nusantara dan dunia, Kapten Klu akhirnya tiba di puncak pertarungan pikiran terakhir. Di sini terbukti bahwa keberanian, kejujuran, dan kebaikan selalu menang melawan kejahatan. Didukung oleh pengetahuan umum yang luas dan semangat yang pantang menyerah, detektif berhasil menyelesaikan komik petualangan dan menyebarkan inspirasi kepada seluruh pemain Tekakomik!",
    words: [
      { id: "off_w21_1", text: "JUJUR", normalizedText: "JUJUR", length: 5, category: "Nilai", difficulty: "EASY" },
      { id: "off_w21_2", text: "PAHLAWAN", normalizedText: "PAHLAWAN", length: 8, category: "Sejarah", difficulty: "MEDIUM" },
      { id: "off_w21_3", text: "SUKSES", normalizedText: "SUKSES", length: 6, category: "Nilai", difficulty: "EASY" },
      { id: "off_w21_4", text: "CERDAS", normalizedText: "CERDAS", length: 6, category: "Nilai", difficulty: "EASY" },
      { id: "off_w21_5", text: "MENANG", normalizedText: "MENANG", length: 6, category: "Status", difficulty: "EASY" },
    ],
  },
];
